IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MaterialStockLedger')
BEGIN
    CREATE TABLE MaterialStockLedger (
        Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        MaterialId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Materials(Id),
        AddedQuantity DECIMAL(18,2) NOT NULL,
        PurchaseRate DECIMAL(18,2) NOT NULL,
        CreatedAt DATETIME DEFAULT SYSDATETIME()
    );
END
GO
