CREATE TABLE PasswordResetTokens (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    ResetToken NVARCHAR(256) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    ExpiresAtUtc DATETIME2 NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_PasswordResetTokens_Users FOREIGN KEY (UserId) REFERENCES users(id) ON DELETE CASCADE
);

